//! Compile per-agent guardrails into **Tetragon** policies — the kernel (eBPF) enforcement ring
//! (`planning/security-model.md`). This is the per-UID layer: non-bypassable from userspace,
//! scoped per agent (one Linux user per agent).
//!
//! Pure: this module only *renders* the policy artifact. Installing Tetragon and loading the
//! policy is [`crate::deploy::TetragonDeployer`]'s job. **The rendered YAML is a generated DRAFT**
//! — the exact TracingPolicy selector schema for per-UID scoping must be validated against the
//! Tetragon version actually installed in the VM before it is relied upon for enforcement.
//!
//! Scope today: syscall hardening (deny a curated set of dangerous syscalls for agent UIDs) plus
//! a documented egress posture carried from the agent's guardrails. Filesystem path enforcement
//! is a natural extension (Tetragon's file layer) and is noted but not yet emitted.

use crate::config::{Config, Guardrails, UserRole};

/// Dangerous syscalls denied for agent UIDs by default. From `planning/security-model.md`
/// (ptrace / mount / kexec) plus standard container-hardening additions (module loading, bpf,
/// namespace manipulation). The human operator is never restricted.
pub const DANGEROUS_SYSCALLS: &[&str] = &[
    "ptrace",
    "mount",
    "umount2",
    "kexec_load",
    "init_module",
    "finit_module",
    "delete_module",
    "setns",
    "unshare",
    "bpf",
    "perf_event_open",
    "reboot",
];

/// A compiled Tetragon policy for one agent (one Linux user / UID).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TetragonPolicy {
    pub name: String,
    pub sandbox: String,
    pub agent: String,
    /// Syscalls denied (Override → -EPERM) for this agent.
    pub denied_syscalls: Vec<String>,
    /// Human-legible egress posture carried from `guardrails.network` (documented in the policy
    /// header; the L3/L4 enforcement itself is the Incus ACL ring — see [`crate::enforce`]).
    pub egress_note: String,
}

/// The deterministic Tetragon policy name for an agent.
pub fn policy_name(sandbox: &str, agent: &str) -> String {
    format!("llmsc-{sandbox}-{agent}")
}

/// Compile one agent's guardrails into a Tetragon policy.
pub fn agent_policy(sandbox: &str, agent: &str, guardrails: Option<&Guardrails>) -> TetragonPolicy {
    let egress_note = guardrails
        .map(|g| g.network.clone())
        .filter(|n| !n.is_empty())
        .unwrap_or_else(|| "unspecified".to_string());
    TetragonPolicy {
        name: policy_name(sandbox, agent),
        sandbox: sandbox.to_string(),
        agent: agent.to_string(),
        denied_syscalls: DANGEROUS_SYSCALLS.iter().map(|s| s.to_string()).collect(),
        egress_note,
    }
}

/// Compile Tetragon policies for every agent in a sandbox (the human operator is excluded).
pub fn sandbox_policies(config: &Config, sandbox: &str) -> Vec<TetragonPolicy> {
    let Some(sb) = config.sandbox(sandbox) else {
        return Vec::new();
    };
    sb.users
        .iter()
        .filter(|u| u.role == UserRole::Agent)
        .map(|u| agent_policy(sandbox, &u.name, u.guardrails.as_ref()))
        .collect()
}

impl TetragonPolicy {
    /// Render the policy as a Tetragon `TracingPolicy` (cilium.io/v1alpha1) YAML. **DRAFT** — see
    /// the module docs: validate the selector schema against the installed Tetragon before relying
    /// on it. Each denied syscall becomes a `kprobe` with an `Override` action returning -EPERM.
    pub fn to_tracing_policy_yaml(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "# Generated by llmsc — DRAFT, validate against the installed Tetragon before relying on it.\n\
             # Per-UID kernel enforcement for agent '{}' in sandbox '{}'.\n\
             # Egress posture (enforced at the Incus ACL ring): {}\n",
            self.agent, self.sandbox, self.egress_note
        ));
        out.push_str("apiVersion: cilium.io/v1alpha1\n");
        out.push_str("kind: TracingPolicy\n");
        out.push_str("metadata:\n");
        out.push_str(&format!("  name: {}\n", self.name));
        out.push_str("spec:\n");
        out.push_str("  kprobes:\n");
        for sc in &self.denied_syscalls {
            out.push_str(&format!("  - call: \"sys_{sc}\"\n"));
            out.push_str("    syscall: true\n");
            out.push_str("    selectors:\n");
            out.push_str("    - matchActions:\n");
            out.push_str("      - action: Override\n");
            out.push_str("        argError: -1\n");
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Config, Guardrails, User, UserRole};

    #[test]
    fn compiles_policies_for_agents_only() {
        let mut cfg = Config::default();
        cfg.upsert_sandbox("web-agent-01", "images:alpine/3.21", false);
        cfg.set_sandbox_user(
            "web-agent-01",
            User {
                name: "colin".into(),
                role: UserRole::Human,
                profile: None,
                guardrails: None,
            },
        );
        cfg.set_sandbox_user(
            "web-agent-01",
            User {
                name: "agent-claude".into(),
                role: UserRole::Agent,
                profile: Some("validation".into()),
                guardrails: Some(Guardrails {
                    network: "None except LLM".into(),
                    ..Default::default()
                }),
            },
        );
        let pols = sandbox_policies(&cfg, "web-agent-01");
        assert_eq!(pols.len(), 1, "human operator is excluded");
        assert_eq!(pols[0].name, "llmsc-web-agent-01-agent-claude");
        assert_eq!(pols[0].egress_note, "None except LLM");
        assert!(pols[0].denied_syscalls.contains(&"ptrace".to_string()));
    }

    #[test]
    fn renders_tracing_policy_yaml() {
        let p = agent_policy("web-agent-01", "agent-claude", None);
        let y = p.to_tracing_policy_yaml();
        assert!(y.contains("kind: TracingPolicy"));
        assert!(y.contains("name: llmsc-web-agent-01-agent-claude"));
        assert!(y.contains("call: \"sys_ptrace\""));
        assert!(y.contains("action: Override"));
        assert!(y.contains("DRAFT"));
        // unspecified egress when there are no guardrails.
        assert!(y.contains("Egress posture (enforced at the Incus ACL ring): unspecified"));
    }
}
